### ISSUE TITLE
Repo missing hello_macos.h

### ISSUE THREAD

**Issue by jjrscott** [floooh/objc-ast-experiments#1]
`hello_macos.h` is missing due to `*.h` in `.gitignore`

**Comment by floooh** [comment]
Yeah, that's intended because hello_macos.h is an output file, produced by running:

```
python test.json test_ir.json
python test_ir.json test/hello_macos.h
```

I'll try to wrap this stuff into a more user-friendly and documented git repo later (or probably integrate it into the sokol repository)
